language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
branches:
  only:
    - master
env:
  - TEST_CLUSTER_COMMAND=/tmp/elasticsearch/bin/elasticsearch
install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.tar.gz | tar xz --directory=/tmp/elasticsearch/ --strip-components=1
script:
  - "bundle exec rspec"
