language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
branches:
  only:
    - master
env:
  - ICELASTIC_ELASTICSEARCH_COMMAND=/tmp/elasticsearch/bin/elasticsearch
install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.tar.gz | tar xz --directory=/tmp/elasticsearch/ --strip-components=1
  - cp -r scripts /tmp/elasticsearch
  - bundle install --without development
script:
  - bundle exec rspec
